language: node_js
node_js: stable
services: 
  - mongodb

before_install:
  - npm install

before_script: 
  - sleep 5
  - mongo sljRN --eval 'db.createCollection("usergenerates");'
  - mongo sljRN --eval 'db.usergenerates.save({_id:"User", next:1});'

script:
  - npm run test

after_script:
  - npm run report
  - npm run coverage